import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'AeroGlide Office Chair',
    description: 'Ergonomic mesh chair for ultimate comfort.',
    price: 349.99,
    imageUrl: 'https://picsum.photos/seed/1/600/400',
    imageHint: 'office chair',
    category: 'Furniture',
  },
  {
    id: '2',
    name: 'SoundWave Pro Headphones',
    description: 'Noise-cancelling over-ear headphones.',
    price: 199.5,
    imageUrl: 'https://picsum.photos/seed/2/600/400',
    imageHint: 'headphones',
    category: 'Electronics',
  },
  {
    id: '3',
    name: 'TitanType Mechanical Keyboard',
    description: 'RGB backlit keyboard for gamers and coders.',
    price: 129.0,
    imageUrl: 'https://picsum.photos/seed/3/600/400',
    imageHint: 'keyboard',
    category: 'Electronics',
  },
  {
    id: '4',
    name: 'CrystalView 4K Monitor',
    description: '27-inch monitor with stunning clarity.',
    price: 499.99,
    imageUrl: 'https://picsum.photos/seed/4/600/400',
    imageHint: 'computer monitor',
    category: 'Electronics',
  },
  {
    id: '5',
    name: 'ChronoFit Smart Watch',
    description: 'Track your fitness and stay connected.',
    price: 249.0,
    imageUrl: 'https://picsum.photos/seed/5/600/400',
    imageHint: 'smart watch',
    category: 'Wearables',
  },
  {
    id: '6',
    name: 'BoomBox Mini Speaker',
    description: 'Compact and powerful bluetooth speaker.',
    price: 79.99,
    imageUrl: 'https://picsum.photos/seed/6/600/400',
    imageHint: 'bluetooth speaker',
    category: 'Electronics',
  },
  {
    id: '7',
    name: 'Velocity Runners',
    description: 'Lightweight and responsive running shoes.',
    price: 139.95,
    imageUrl: 'https://picsum.photos/seed/7/600/400',
    imageHint: 'running shoes',
    category: 'Apparel',
  },
  {
    id: '8',
    name: 'HydroFlask Steel Bottle',
    description: 'Keeps your drinks cold for 24 hours.',
    price: 45.0,
    imageUrl: 'https://picsum.photos/seed/8/600/400',
    imageHint: 'water bottle',
    category: 'Accessories',
  },
  {
    id: '9',
    name: 'Lumina Desk Lamp',
    description: 'Modern LED lamp with adjustable brightness.',
    price: 89.5,
    imageUrl: 'https://picsum.photos/seed/9/600/400',
    imageHint: 'desk lamp',
    category: 'Furniture',
  },
  {
    id: '10',
    name: 'Artisan Roast Coffee',
    description: '12oz bag of whole bean medium roast.',
    price: 18.0,
    imageUrl: 'https://picsum.photos/seed/10/600/400',
    imageHint: 'coffee beans',
    category: 'Groceries',
  },
];

export const productCategories = [
  ...new Set(products.map((p) => p.category)),
];
